// <auto-generated/>
namespace Microsoft.Teams.Apps.ListSearch.Configuration
{
    /// <summary>
    /// Mvc Application
    /// </summary>
    public class MvcApplication : System.Web.HttpApplication
    {
    }
}
